### ISSUE TITLE
Array Arguments

### ISSUE THREAD

**Issue by landersson** [LinkTed/dbus-async-derive#1]
Hi,

Could you please provide some example code showing how to pass Array and Struct arguments to D-Bus methods?

**Comment by LinkTed** [comment]
It seems that there were bugs for array and struct arguments. I fixed it in the new version `2.0.1` and add an example (see `examples/container.rs`).

**Comment by LinkTed** [comment]
@landersson By the way, thanks for the info.

**Comment by landersson** [comment]
Seems to work, thanks!
